services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    image: ${DOCKERHUB_USERNAME}/web-ide
    container_name: web_ide
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database

  nginx:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/web-ide.conf:/etc/nginx/sites-enabled/web-ide.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

