services:
#  database:
#    image: mysql:8.0
#    container_name: mysql_db
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#    volumes:
#      - mysql-data:/var/lib/mysql
#    ports:
#      - "3306:3306"

  app:
    image: skdud3229/web-ide
    container_name: web_ide
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
#    depends_on:
#      - database

  nginx:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/web-ide.conf:/etc/nginx/sites-enabled/web-ide.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

